[package]
name = "rust_d3_geo_voronoi"
version = "0.1.0"
authors = ["martin frances <martinfrances107@hotmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
measureme = "9.0.0"
geojson = "0.20.0"
geo="0.15.0"
delaunator = { git = "https://github.com/mourner/delaunator-rs.git" }
rust_d3_array = { git = "https://github.com/martinfrances107/rust_d3_array.git" }
rust_d3_delaunay = { git = "https://github.com/martinfrances107/rust_d3_delaunay.git", branch = "main" }
rust_d3_geo = { git = "https://github.com/martinfrances107/rust_d3_geo.git" }

[dev-dependencies]
pretty_assertions = "0.6.1"