[package]
name = "rust_d3_geo_voronoi"
version = "0.1.0"
authors = ["martin frances <martinfrances107@hotmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
measureme = "0.7.1"
geojson = "0.19.0"
geo="0.14.2"
num-traits="0.2.12"
rust_d3_geo = {path = "../rust_d3_geo"}
rust_d3_array = {path = "../rust_d3_array"}

[dev-dependencies]
pretty_assertions = "0.6.1"