[workspace]
members = [
    "./lib",
    "./benchmark",      # A webpage with a stress test of the library.
    "./profile_target", # A binary that output a compelex SVG images, which can be profiled.
]

[workspace.dependencies]
geo = "0.23.0"
rust_d3_geo = { git = "https://github.com/martinfrances107/rust_d3_geo.git", branch = "main" }
rust_d3_delaunay = { git = "https://github.com/martinfrances107/rust_d3_delaunay.git", branch = "main" }

[profile.release]
# This makes the compiled code faster and smaller, but it makes compiling slower,
# so it's only enabled in release mode.
lto = true
debug = true
codegen-units = 1

[profile.dev]
debug = true

# patch over the latest release with a version that adds
# cyclic_match for test builds.
#
# Only "./lib" needs this extra functionality.
[patch.crates-io]
geo = { git = "https://github.com/martinfrances107/geo.git", branch = "cyclic_match", package = "geo" }
