[workspace]
members = [
    "./lib",
    "./benchmark",
    "./profile_target"
]

[profile.release]
# This makes the compiled code faster and smaller, but it makes compiling slower,
# so it's only enabled in release mode.
lto = true
debug = 2

# Needed by benchmark, debug symbols are essential.
[profile.dev]
debug=2

# patch over the latest release with a version that adds
# cyclic_match for test builds.
#
# Only "./lib" needs this extra functionality.
[patch.crates-io]
# geo = { path = "../geo/geo/", feature=["use-approx"]}
geo = { git = "https://github.com/martinfrances107/geo.git", branch="cyclic_match", package="geo", feature=["use-approx"]}

