[package]
name = "profile_target"
version = "0.1.0"
description = "Generates a SVG file for profiling."
license = "MIT"
authors = ["martin <martinfrances107@hotmail.com>"]
edition = "2021"

[dependencies]
geo = "0.23.0"
rust_d3_geo_voronoi = { path = "../lib" }
rust_d3_geo = { git = "https://github.com/martinfrances107/rust_d3_geo.git", branch = "main" }
rust_d3_delaunay = { git = "https://github.com/martinfrances107/rust_d3_delaunay.git", branch = "main" }

getrandom = { version = "0.2.3", features = ["js"] }
rand = { version = "0.8.4" }
lazy_static = "1.4.0"
flamegraph = "0.6.2"
